/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dictionary': RouteRecordInfo<'/dictionary', '/dictionary', Record<never, never>, Record<never, never>>,
    '/essays/': RouteRecordInfo<'/essays/', '/essays', Record<never, never>, Record<never, never>>,
    '/essays/[id]': RouteRecordInfo<'/essays/[id]', '/essays/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/new-essay': RouteRecordInfo<'/new-essay', '/new-essay', Record<never, never>, Record<never, never>>,
    '/progress': RouteRecordInfo<'/progress', '/progress', Record<never, never>, Record<never, never>>,
  }
}
