/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dictionary': RouteRecordInfo<
      '/dictionary',
      '/dictionary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/essays/': RouteRecordInfo<
      '/essays/',
      '/essays',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/essays/[id]': RouteRecordInfo<
      '/essays/[id]',
      '/essays/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/new-essay': RouteRecordInfo<
      '/new-essay',
      '/new-essay',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/progress': RouteRecordInfo<
      '/progress',
      '/progress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/dictionary.vue': {
      routes:
        | '/dictionary'
      views:
        | never
    }
    'src/pages/essays/index.vue': {
      routes:
        | '/essays/'
      views:
        | never
    }
    'src/pages/essays/[id].vue': {
      routes:
        | '/essays/[id]'
      views:
        | never
    }
    'src/pages/new-essay.vue': {
      routes:
        | '/new-essay'
      views:
        | never
    }
    'src/pages/progress.vue': {
      routes:
        | '/progress'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
